# Generated by Django 2.1 on 2018-11-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Location', models.CharField(choices=[('Arusha', 'Arusha'), ('Dar es salaam', 'Dar es salaam'), ('Dodoma', 'Dodoma'), ('Morogoro', 'Morogoro'), ('Bukoba', 'Bukoba'), ('Moshi', 'Moshi'), ('Kilimanjaro', 'Kilimanjaro'), ('Singida', 'Singida'), ('Tabora', 'Tabora'), ('Tanga', 'Tanga'), ('Iringa', 'Iringa'), ('Songea', 'Songea'), ('Mbeya', 'Mbeya'), ('Mtwara', 'Mtwara'), ('Ruvuma', 'Ruvuma'), ('Kigoma', 'Kigoma'), ('Mombasa', 'Mombasa'), ('Mwanza', 'Mwanza'), ('Babati', 'Babati'), ('Sumbawanga', 'Sumbawanga')], max_length=50)),
                ('Type', models.CharField(choices=[('For rent', 'For rent'), ('For sell', 'For sell')], max_length=50)),
                ('Number_of_bedrooms', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50)),
                ('Image', models.CharField(max_length=200)),
                ('Price', models.CharField(max_length=20)),
                ('Description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'House Property',
            },
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Location', models.CharField(choices=[('Arusha', 'Arusha'), ('Dar es salaam', 'Dar es salaam'), ('Dodoma', 'Dodoma'), ('Morogoro', 'Morogoro'), ('Bukoba', 'Bukoba'), ('Moshi', 'Moshi'), ('Kilimanjaro', 'Kilimanjaro'), ('Singida', 'Singida'), ('Tabora', 'Tabora'), ('Tanga', 'Tanga'), ('Iringa', 'Iringa'), ('Songea', 'Songea'), ('Mbeya', 'Mbeya'), ('Mtwara', 'Mtwara'), ('Ruvuma', 'Ruvuma'), ('Kigoma', 'Kigoma'), ('Mombasa', 'Mombasa'), ('Mwanza', 'Mwanza'), ('Babati', 'Babati'), ('Sumbawanga', 'Sumbawanga')], max_length=50)),
                ('Area', models.CharField(max_length=50)),
                ('Image', models.CharField(max_length=200)),
                ('Price', models.CharField(max_length=20)),
                ('Description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Land Property',
            },
        ),
    ]
